services:
  backend:
    env_file: "./env/.env.production"
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PYTHONUNBUFFERED=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`terminal.johnling.me`)
      - "traefik.http.routers.backend.entrypoints=backend"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
    networks:
      - lingux-network

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
      args:
        - VITE_API_BASE_URL=https://terminal.johnling.me:8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.guestbook.rule=Host(`terminal.johnling.me`)"
      - "traefik.http.routers.guestbook.entrypoints=websecure"
      - "traefik.http.routers.guestbook.tls.certresolver=letsencrypt"
    networks:
      - lingux-network

  reverse-proxy:
    image: traefik:3.6
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.backend.address=:8000" 
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=johnlingbusiness@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt
    networks:
      - lingux-network
  
volumes:
  letsencrypt: 

networks:
  lingux-network:
    driver: bridge
